version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - mynet
  cache:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - mynet

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
    networks:
      - mynet
volumes:
  db:
    driver: local

networks:
  mynet:
    driver: bridge